Updated dependencies
auth0/Lock-Google.iOS pull request #15
Opened 2016-12-22 16:21 UTC by cocojoe

Removed retired Google SignIn code
Updated tests
Cleaned up podfile

2017-01-09 00:12 UTC, hzalaz requested changes

2017-01-09 00:12 UTC, hzalaz commented on .travis.yml
> +- set -o pipefail && xcodebuild test -workspace LockGoogle.xcworkspace -scheme LockGoogle -destination 'id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355' | xcpretty -c
I believe the ids can change from installation to installation so we should use names instead

2017-01-09 00:12 UTC, hzalaz commented on LockGoogleApp/Info.plist
> +	<string>brucke.auth0.com</string>
We should not commit clientid of this tenant (removed it from dashboard already) so put back the old ones

2017-01-09 10:28 UTC, cocojoe commented on LockGoogleApp/Info.plist
> +	<string>brucke.auth0.com</string>
No problem, I wasn't sure, should have double checked with you.  The intention was to leave it as a working example (previous one wasn't).

2017-01-09 10:38 UTC, cocojoe commented on .travis.yml
> +- set -o pipefail && xcodebuild test -workspace LockGoogle.xcworkspace -scheme LockGoogle -destination 'id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355' | xcpretty -c
I went through many iterations as the names setup just wouldn't work (see travis PR history). There is an ongoing issue and the 'solution' for now is to specify id.

https://discuss.circleci.com/t/multiple-ios-simulators-available-for-single-os-device-configurations/7854

2017-01-17 16:38 UTC, hzalaz approved these changes

2017-01-17 16:38 UTC, merged